### ISSUE TITLE
Why are all the datasets I download black or gray

### ISSUE THREAD

**Issue by zh-he** [MatPiech/motor-fault-diagnosis#11]

**Comment by MatPiech** [comment]
Your question is a duplication of one from a closed issue - #7 

These images were registered and are stored as raw uint16 values. To get color visualization you have e.g. to rescale these data to the 0-1 range or visualize with matplotlib imshow, which does the same before preview.

Here is an example code in Python:

```python
import matplotlib.pyplot as plt
import numpy as np
from PIL import Image


def normalize(data):
    return (data - data.min()) / (data.max() - data.min())


img_raw = np.asarray(Image.open(filepath), dtype=np.uint16)
img = normalize(img_raw)
plt.imshow(img, cmap='inferno')
```

Let me know if it resolves your concerns.
