### ISSUE TITLE
Sorry to bother you, why are all the black and gray images in the downloaded dataset

### ISSUE THREAD

**Issue by Lion-CTGU** [MatPiech/motor-fault-diagnosis#7]

**Comment by MatPiech** [comment]
Hello!

The images were captured in UINT16 raw data format and in this format, they
are stored. To obtain images as in the repository README you have to normalize
them e.g. to the 0-1 range (or 0-255) or use a function to visualize them, which
do this normalization like [imshow](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.imshow.html) from matplotlib library.

Best!

**Comment by Lion-CTGU** [comment]
Thank you for your reply. Also, do you have any specific information about this motor that you collected, such as its speed, load, the picture of motor and so on

**Comment by MatPiech** [comment]
It will be described in an upcoming scientific paper.

**Comment by Lion-CTGU** [comment]
ok,thank you.Will it be posted on your GitHub?

---Original---
From: "Mateusz ***@***.***&gt;
Date: Tue, May 9, 2023 22:38 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [MatPiech/motor-fault-diagnosis] Sorry to bother you, why are allthe black and gray images in the downloaded dataset (Issue #7)




 
It will be described in an upcoming scientific paper.

**Comment by MatPiech** [comment]
It will be linked to the publisher page as soon as it will be published. The article will have an Open Access format.

**Comment by Lion-CTGU** [comment]
But i don't know the name of this article.i can't download to read it. I mean that i don't know what article use this dataset.I very thank your reply.



---Original---
From: "Mateusz ***@***.***&gt;
Date: Tue, May 9, 2023 22:47 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [MatPiech/motor-fault-diagnosis] Sorry to bother you, why are allthe black and gray images in the downloaded dataset (Issue #7)




 
It will be linked to the publisher page as soon as it will be published. The article will have an Open Access format.

**Comment by MatPiech** [comment]
@Lion-CTGU our paper _[Unraveling Induction Motor State through Thermal Imaging and Edge Processing: A Step towards Explainable Fault Diagnosis](https://ein.org.pl/Unraveling-Induction-Motor-State-through-Thermal-Imaging-and-Edge-Processing-A-Step,170114,0,2.html)_ is finally available (DOI: [https://doi.org/10.17531/ein/170114](https://doi.org/10.17531/ein/170114)). Let me know if it covers all your questions!

**Comment by Lion-CTGU** [comment]
Yes, I got it. thanks, my friend.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MatPiech/motor-fault-diagnosis"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月31日(星期一) 下午5:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MatPiech/motor-fault-diagnosis] Sorry to bother you, why are all the black and gray images in the downloaded dataset (Issue #7)





 
@Lion-CTGU our paper Unraveling Induction Motor State through Thermal Imaging and Edge Processing: A Step towards Explainable Fault Diagnosis is finally available (DOI: https://doi.org/10.17531/ein/170114). Let me know if it covers all your questions!
